language: node_js
node_js:
  - 14.15.3

cache:
  directories:
    - "node_modules"
    - "target"

jobs:
  include:
    - stage: install
      script:
        - npm i -q
    - stage: compile
      script:
        - npm run build
    - stage: test
      script:
        - npm t
    - stage: release
      script:
        - npx semantic-release
